### ISSUE TITLE
typo in 01-intro.mdx ?

### ISSUE THREAD

**Issue by gedw99** [ogen-go/web#44]
on https://github.com/ogen-go/web/blob/main/docs/01-intro.mdx

Shoudl be "./petstore.yml", not "./swagger-petstore.yml" ??

``` 
//go:generate go run github.com/ogen-go/ogen/cmd/ogen --schema ./petstore.yml --target petstore --clean
```

**Comment by ernado** [comment]
Yes, it is typo
